"""update info

Revision ID: 21c0097faf2c
Revises: 82d801f52ce
Create Date: 2015-02-03 23:46:47.110025

"""

# revision identifiers, used by Alembic.
revision = '21c0097faf2c'
down_revision = '82d801f52ce'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('arm_length', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('arm_width', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('info', sa.Column('butt', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('chest', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('leg_length', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('leg_width', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('neck', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('sex', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('shoulder', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('waist', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('info', sa.Column('weixin_avatar', sa.String(length=100), nullable=True))
    op.add_column('info', sa.Column('weixin_id', sa.String(length=100), nullable=True))
    op.add_column('info', sa.Column('weixin_name', sa.String(length=100), nullable=True))
    op.drop_column('info', 'weixin')
    op.drop_column('info', 'props')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('info', sa.Column('props', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('info', sa.Column('weixin', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('info', 'weixin_name')
    op.drop_column('info', 'weixin_id')
    op.drop_column('info', 'weixin_avatar')
    op.drop_column('info', 'weight')
    op.drop_column('info', 'waist')
    op.drop_column('info', 'shoulder')
    op.drop_column('info', 'sex')
    op.drop_column('info', 'neck')
    op.drop_column('info', 'leg_width')
    op.drop_column('info', 'leg_length')
    op.drop_column('info', 'height')
    op.drop_column('info', 'chest')
    op.drop_column('info', 'butt')
    op.drop_column('info', 'birthday')
    op.drop_column('info', 'arm_width')
    op.drop_column('info', 'arm_length')
    ### end Alembic commands ###
