"""empty message

Revision ID: 82d801f52ce
Revises: None
Create Date: 2014-12-08 10:43:23.241551

"""

# revision identifiers, used by Alembic.
revision = '82d801f52ce'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weixin', sa.String(length=100), nullable=True),
    sa.Column('props', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info')
    ### end Alembic commands ###
